entryPoints:
  web:
    address: ":80"

providers:
  docker:
    exposedByDefault: false

api:
  dashboard: true
  insecure: true

log:
  level: INFO

accessLog: 
  filePath: "/var/log/traefik/access.log"
  format: json

